stages:
    - deploy

pages:
  stage: deploy
  image: jeonghanlee/mdbook
  script:
    - mdbook build -d public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - public