[book]
authors = ["Jeong Han Lee"]
language = "en"
multilingual = false
src = "docs"
title = "ALS-U EPICS Envorinment Distribution"

[build]
build-dir = "public"

[output.html]
#additional-css = ["./assets/custom.css"]

[preprocessor.toc]
command = "./mdbook-toc"
renderer = ["html"]

