# https://rust-lang.github.io/mdBook/format/configuration/general.html
[book]
title = "ALS-U EPICS Envorinment Distribution Training"
authors = ["Jeong Han Lee"]
src = "docs"
language = "en"
multilingual = false

[build]
build-dir = "public"

